name: Windows build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  CRAFT_TARGET: windows-msvc2022_64
  CRAFT_MASTER_LOCATION: ${{ github.workspace }}/CraftMaster
  CRAFT_MASTER_CONFIG: ${{ github.workspace }}/craftmaster.ini

jobs:
  build:
    name: Build ghostwriter
    runs-on: windows-2022

    steps:
      - name: Checkout workflow
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Download CraftMaster
        shell: pwsh
        run: |
          git clone -q --depth=1 `
            https://invent.kde.org/packaging/craftmaster.git `
            "$env:CRAFT_MASTER_LOCATION"

      - name: Set up Craft
        shell: pwsh
        run: |
          python "$env:CRAFT_MASTER_LOCATION/CraftMaster.py" `
            --config "$env:CRAFT_MASTER_CONFIG" `
            --target "$env:CRAFT_TARGET" `
            -c craft

      - name: Create ghostwriter blueprint
        shell: pwsh
        run: |
          $blueprintDir = `
            "${{ github.workspace }}\ghostwriter-blueprints\kde\ghostwriter"

          New-Item `
            -ItemType Directory `
            -Force `
            -Path $blueprintDir | Out-Null

          @'
          import info

          from Package.CMakePackageBase import CMakePackageBase


          class subinfo(info.infoclass):

              def setTargets(self):
                  self.displayName = "ghostwriter"
                  self.description = "Text editor for Markdown"
                  self.webpage = "https://github.com/KDE/ghostwriter"

                  self.svnTargets["master"] = \
                      "https://github.com/KDE/ghostwriter.git|master"

                  self.defaultTarget = "master"

              def setDependencies(self):
                  self.buildDependencies[
                      "kde/frameworks/extra-cmake-modules"
                  ] = None

                  self.runtimeDependencies["libs/qt/qtbase"] = None
                  self.runtimeDependencies["libs/qt/qtsvg"] = None
                  self.runtimeDependencies["libs/qt/qtwebchannel"] = None
                  self.runtimeDependencies["libs/qt/qtwebengine"] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier1/kcoreaddons"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier1/kwidgetsaddons"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier1/sonnet"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier2/kconfig"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier3/kconfigwidgets"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier3/kxmlgui"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier1/breeze-icons"
                  ] = None

                  self.runtimeDependencies[
                      "kde/frameworks/tier3/kiconthemes"
                  ] = None


          class Package(CMakePackageBase):

              def __init__(self, **args):
                  CMakePackageBase.__init__(self, **args)

              def createPackage(self):
                  self.defines["appname"] = "ghostwriter"
                  self.defines["shortcuts"] = [{
                      "name": "ghostwriter",
                      "target": "bin/ghostwriter.exe"
                  }]
                  return super().createPackage()
          '@ | Set-Content `
            -Encoding UTF8 `
            "$blueprintDir\ghostwriter.py"

      - name: Build ghostwriter
        shell: pwsh
        run: |
          python "$env:CRAFT_MASTER_LOCATION/CraftMaster.py" `
            --config "$env:CRAFT_MASTER_CONFIG" `
            --target "$env:CRAFT_TARGET" `
            --add-blueprint-repository `
            "${{ github.workspace }}/ghostwriter-blueprints" `
            -c `
            --options ghostwriter.srcDir="${{ github.workspace }}/upstream" `
            ghostwriter
